"""Dodanie kolumny price

Revision ID: 0e70ed06f4c0
Revises: 62b253df28b6
Create Date: 2020-02-19 20:39:58.200444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e70ed06f4c0'
down_revision = '62b253df28b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advert', sa.Column('price', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('advert', 'price')
    # ### end Alembic commands ###
