"""empty message

Revision ID: 314f34df9036
Revises: 0e70ed06f4c0
Create Date: 2020-02-19 21:00:10.231652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '314f34df9036'
down_revision = '0e70ed06f4c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('advert', 'price',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('advert', 'price',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)
    # ### end Alembic commands ###
